function set_3d_figs(views, xpos, xlims, ypos, ylims, zpos, zlims)
    view(views)
    xlim(xlims)
    ylim(ylims)
    zlim(zlims)
    xlabel('x','fontsize',24,'position',xpos)
    ylabel('t','fontsize',24,'position',ypos)
    zlabel('u','fontsize',24,'rotation',0,'position',zpos)
    set(gca,'xtick',[],'xticklabel',[],'ytick',[],'yticklabel',[],'zticklabel',[])
    set(gcf,'color','w')
end